/*
 * Paperless Rest Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PaperlessREST.Entities.Converters;

namespace PaperlessREST.Entities
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
<<<<<<<< HEAD:src/PaperlessREST.Entities/ApiuiSettingsSettingsDocumentDetails.cs
    public partial class ApiuiSettingsSettingsDocumentDetails : IEquatable<ApiuiSettingsSettingsDocumentDetails>
========
    public partial class CreateUISettingsRequestSettingsDocumentDetails : IEquatable<CreateUISettingsRequestSettingsDocumentDetails>
>>>>>>>> dev:src/PaperlessREST.Entities/CreateUISettingsRequestSettingsDocumentDetails.cs
    {
        /// <summary>
        /// Gets or Sets NativePdfViewer
        /// </summary>
        [Required]
<<<<<<<< HEAD:src/PaperlessREST.Entities/ApiuiSettingsSettingsDocumentDetails.cs

        [DataMember(Name = "native_pdf_viewer")]
        public bool? NativePdfViewer { get; set; }
========
        [DataMember(Name = "native_pdf_viewer", EmitDefaultValue = true)]
        public bool NativePdfViewer { get; set; }
>>>>>>>> dev:src/PaperlessREST.Entities/CreateUISettingsRequestSettingsDocumentDetails.cs

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateUISettingsRequestSettingsDocumentDetails {\n");
            sb.Append("  NativePdfViewer: ").Append(NativePdfViewer).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateUISettingsRequestSettingsDocumentDetails)obj);
        }

        /// <summary>
        /// Returns true if CreateUISettingsRequestSettingsDocumentDetails instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateUISettingsRequestSettingsDocumentDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateUISettingsRequestSettingsDocumentDetails other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                
                    NativePdfViewer == other.NativePdfViewer ||

                    NativePdfViewer.Equals(other.NativePdfViewer)
                ;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
<<<<<<<< HEAD:src/PaperlessREST.Entities/ApiuiSettingsSettingsDocumentDetails.cs
                if (NativePdfViewer != null)
                    hashCode = hashCode * 59 + NativePdfViewer.GetHashCode();
========

                hashCode = hashCode * 59 + NativePdfViewer.GetHashCode();
>>>>>>>> dev:src/PaperlessREST.Entities/CreateUISettingsRequestSettingsDocumentDetails.cs
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(CreateUISettingsRequestSettingsDocumentDetails left, CreateUISettingsRequestSettingsDocumentDetails right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateUISettingsRequestSettingsDocumentDetails left, CreateUISettingsRequestSettingsDocumentDetails right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
