/*
 * Paperless Rest Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PaperlessREST.Entities
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DocumentType : IEquatable<DocumentType>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
<<<<<<< HEAD

        [DataMember(Name = "id")]
        public long? Id { get; set; }
=======
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public long Id { get; set; }
>>>>>>> dev

        /// <summary>
        /// Gets or Sets Slug
        /// </summary>
<<<<<<< HEAD

        [DataMember(Name = "slug")]
=======
        [DataMember(Name = "slug", EmitDefaultValue = true)]
>>>>>>> dev
        public string Slug { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
<<<<<<< HEAD

        [DataMember(Name = "name")]
=======
        [DataMember(Name = "name", EmitDefaultValue = true)]
>>>>>>> dev
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Match
        /// </summary>
<<<<<<< HEAD

        [DataMember(Name = "match")]
=======
        [DataMember(Name = "match", EmitDefaultValue = true)]
>>>>>>> dev
        public string Match { get; set; }

        /// <summary>
        /// Gets or Sets MatchingAlgorithm
        /// </summary>
<<<<<<< HEAD

        [DataMember(Name = "matching_algorithm")]
        public long? MatchingAlgorithm { get; set; }
=======
        [DataMember(Name = "matching_algorithm", EmitDefaultValue = true)]
        public long MatchingAlgorithm { get; set; }
>>>>>>> dev

        /// <summary>
        /// Gets or Sets IsInsensitive
        /// </summary>
<<<<<<< HEAD

        [DataMember(Name = "is_insensitive")]
        public bool? IsInsensitive { get; set; }
=======
        [DataMember(Name = "is_insensitive", EmitDefaultValue = true)]
        public bool IsInsensitive { get; set; }
>>>>>>> dev

        /// <summary>
        /// Gets or Sets DocumentCount
        /// </summary>
<<<<<<< HEAD

        [DataMember(Name = "document_count")]
        public long? DocumentCount { get; set; }
=======
        [DataMember(Name = "document_count", EmitDefaultValue = true)]
        public long DocumentCount { get; set; }
>>>>>>> dev

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocumentType {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Slug: ").Append(Slug).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Match: ").Append(Match).Append("\n");
            sb.Append("  MatchingAlgorithm: ").Append(MatchingAlgorithm).Append("\n");
            sb.Append("  IsInsensitive: ").Append(IsInsensitive).Append("\n");
            sb.Append("  DocumentCount: ").Append(DocumentCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DocumentType)obj);
        }

        /// <summary>
        /// Returns true if DocumentType instances are equal
        /// </summary>
        /// <param name="other">Instance of DocumentType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocumentType other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Id == other.Id ||

                    Id.Equals(other.Id)
                ) &&
                (
                    Slug == other.Slug ||
                    Slug != null &&
                    Slug.Equals(other.Slug)
                ) &&
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) &&
                (
                    Match == other.Match ||
                    Match != null &&
                    Match.Equals(other.Match)
                ) &&
                (
                    MatchingAlgorithm == other.MatchingAlgorithm ||

                    MatchingAlgorithm.Equals(other.MatchingAlgorithm)
                ) &&
                (
                    IsInsensitive == other.IsInsensitive ||

                    IsInsensitive.Equals(other.IsInsensitive)
                ) &&
                (
                    DocumentCount == other.DocumentCount ||

                    DocumentCount.Equals(other.DocumentCount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
<<<<<<< HEAD
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
=======

                hashCode = hashCode * 59 + Id.GetHashCode();
>>>>>>> dev
                if (Slug != null)
                    hashCode = hashCode * 59 + Slug.GetHashCode();
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (Match != null)
                    hashCode = hashCode * 59 + Match.GetHashCode();
<<<<<<< HEAD
                if (MatchingAlgorithm != null)
                    hashCode = hashCode * 59 + MatchingAlgorithm.GetHashCode();
                if (IsInsensitive != null)
                    hashCode = hashCode * 59 + IsInsensitive.GetHashCode();
                if (DocumentCount != null)
                    hashCode = hashCode * 59 + DocumentCount.GetHashCode();
=======

                hashCode = hashCode * 59 + MatchingAlgorithm.GetHashCode();

                hashCode = hashCode * 59 + IsInsensitive.GetHashCode();

                hashCode = hashCode * 59 + DocumentCount.GetHashCode();
>>>>>>> dev
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(DocumentType left, DocumentType right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DocumentType left, DocumentType right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
