/*
 * Paperless Rest Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PaperlessREST.Entities.Converters;

namespace PaperlessREST.Entities
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
<<<<<<<< HEAD:src/PaperlessREST.Entities/InlineResponse2006.cs
    public partial class InlineResponse2006 : IEquatable<InlineResponse2006>
========
    public partial class GetDocumentSuggestions200Response : IEquatable<GetDocumentSuggestions200Response>
>>>>>>>> dev:src/PaperlessREST.Entities/GetDocumentSuggestions200Response.cs
    {
        /// <summary>
        /// Gets or Sets Correspondents
        /// </summary>
        [Required]
<<<<<<<< HEAD:src/PaperlessREST.Entities/InlineResponse2006.cs

        [DataMember(Name = "correspondents")]
========
        [DataMember(Name = "correspondents", EmitDefaultValue = false)]
>>>>>>>> dev:src/PaperlessREST.Entities/GetDocumentSuggestions200Response.cs
        public List<object> Correspondents { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [Required]
<<<<<<<< HEAD:src/PaperlessREST.Entities/InlineResponse2006.cs

        [DataMember(Name = "tags")]
========
        [DataMember(Name = "tags", EmitDefaultValue = false)]
>>>>>>>> dev:src/PaperlessREST.Entities/GetDocumentSuggestions200Response.cs
        public List<object> Tags { get; set; }

        /// <summary>
        /// Gets or Sets DocumentTypes
        /// </summary>
        [Required]
<<<<<<<< HEAD:src/PaperlessREST.Entities/InlineResponse2006.cs

        [DataMember(Name = "document_types")]
========
        [DataMember(Name = "document_types", EmitDefaultValue = false)]
>>>>>>>> dev:src/PaperlessREST.Entities/GetDocumentSuggestions200Response.cs
        public List<object> DocumentTypes { get; set; }

        /// <summary>
        /// Gets or Sets StoragePaths
        /// </summary>
        [Required]
<<<<<<<< HEAD:src/PaperlessREST.Entities/InlineResponse2006.cs

        [DataMember(Name = "storage_paths")]
========
        [DataMember(Name = "storage_paths", EmitDefaultValue = false)]
>>>>>>>> dev:src/PaperlessREST.Entities/GetDocumentSuggestions200Response.cs
        public List<object> StoragePaths { get; set; }

        /// <summary>
        /// Gets or Sets Dates
        /// </summary>
        [Required]
<<<<<<<< HEAD:src/PaperlessREST.Entities/InlineResponse2006.cs

        [DataMember(Name = "dates")]
========
        [DataMember(Name = "dates", EmitDefaultValue = false)]
>>>>>>>> dev:src/PaperlessREST.Entities/GetDocumentSuggestions200Response.cs
        public List<object> Dates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetDocumentSuggestions200Response {\n");
            sb.Append("  Correspondents: ").Append(Correspondents).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  DocumentTypes: ").Append(DocumentTypes).Append("\n");
            sb.Append("  StoragePaths: ").Append(StoragePaths).Append("\n");
            sb.Append("  Dates: ").Append(Dates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GetDocumentSuggestions200Response)obj);
        }

        /// <summary>
        /// Returns true if GetDocumentSuggestions200Response instances are equal
        /// </summary>
        /// <param name="other">Instance of GetDocumentSuggestions200Response to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetDocumentSuggestions200Response other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Correspondents == other.Correspondents ||
                    Correspondents != null &&
                    other.Correspondents != null &&
                    Correspondents.SequenceEqual(other.Correspondents)
                ) &&
                (
                    Tags == other.Tags ||
                    Tags != null &&
                    other.Tags != null &&
                    Tags.SequenceEqual(other.Tags)
                ) &&
                (
                    DocumentTypes == other.DocumentTypes ||
                    DocumentTypes != null &&
                    other.DocumentTypes != null &&
                    DocumentTypes.SequenceEqual(other.DocumentTypes)
                ) &&
                (
                    StoragePaths == other.StoragePaths ||
                    StoragePaths != null &&
                    other.StoragePaths != null &&
                    StoragePaths.SequenceEqual(other.StoragePaths)
                ) &&
                (
                    Dates == other.Dates ||
                    Dates != null &&
                    other.Dates != null &&
                    Dates.SequenceEqual(other.Dates)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Correspondents != null)
                    hashCode = hashCode * 59 + Correspondents.GetHashCode();
                if (Tags != null)
                    hashCode = hashCode * 59 + Tags.GetHashCode();
                if (DocumentTypes != null)
                    hashCode = hashCode * 59 + DocumentTypes.GetHashCode();
                if (StoragePaths != null)
                    hashCode = hashCode * 59 + StoragePaths.GetHashCode();
                if (Dates != null)
                    hashCode = hashCode * 59 + Dates.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(GetDocumentSuggestions200Response left, GetDocumentSuggestions200Response right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GetDocumentSuggestions200Response left, GetDocumentSuggestions200Response right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
