/*
 * Paperless Rest Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PaperlessREST.Entities.Converters;

namespace PaperlessREST.Entities
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
<<<<<<<< HEAD:src/PaperlessREST.Entities/ApistoragePathsidPermissions.cs
    public partial class ApistoragePathsidPermissions : IEquatable<ApistoragePathsidPermissions>
========
    public partial class GetStoragePaths200ResponseResultsInnerPermissions : IEquatable<GetStoragePaths200ResponseResultsInnerPermissions>
>>>>>>>> dev:src/PaperlessREST.Entities/GetStoragePaths200ResponseResultsInnerPermissions.cs
    {
        /// <summary>
        /// Gets or Sets View
        /// </summary>
        [Required]
<<<<<<<< HEAD:src/PaperlessREST.Entities/ApistoragePathsidPermissions.cs

        [DataMember(Name = "view")]
        public ApistoragePathsidPermissionsView View { get; set; }
========
        [DataMember(Name = "view", EmitDefaultValue = false)]
        public GetStoragePaths200ResponseResultsInnerPermissionsView View { get; set; }
>>>>>>>> dev:src/PaperlessREST.Entities/GetStoragePaths200ResponseResultsInnerPermissions.cs

        /// <summary>
        /// Gets or Sets Change
        /// </summary>
        [Required]
<<<<<<<< HEAD:src/PaperlessREST.Entities/ApistoragePathsidPermissions.cs

        [DataMember(Name = "change")]
        public ApistoragePathsidPermissionsView Change { get; set; }
========
        [DataMember(Name = "change", EmitDefaultValue = false)]
        public GetStoragePaths200ResponseResultsInnerPermissionsView Change { get; set; }
>>>>>>>> dev:src/PaperlessREST.Entities/GetStoragePaths200ResponseResultsInnerPermissions.cs

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetStoragePaths200ResponseResultsInnerPermissions {\n");
            sb.Append("  View: ").Append(View).Append("\n");
            sb.Append("  Change: ").Append(Change).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GetStoragePaths200ResponseResultsInnerPermissions)obj);
        }

        /// <summary>
        /// Returns true if GetStoragePaths200ResponseResultsInnerPermissions instances are equal
        /// </summary>
        /// <param name="other">Instance of GetStoragePaths200ResponseResultsInnerPermissions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetStoragePaths200ResponseResultsInnerPermissions other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    View == other.View ||
                    View != null &&
                    View.Equals(other.View)
                ) &&
                (
                    Change == other.Change ||
                    Change != null &&
                    Change.Equals(other.Change)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (View != null)
                    hashCode = hashCode * 59 + View.GetHashCode();
                if (Change != null)
                    hashCode = hashCode * 59 + Change.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(GetStoragePaths200ResponseResultsInnerPermissions left, GetStoragePaths200ResponseResultsInnerPermissions right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GetStoragePaths200ResponseResultsInnerPermissions left, GetStoragePaths200ResponseResultsInnerPermissions right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
