/*
 * Paperless Rest Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using PaperlessREST.Attributes;
<<<<<<< HEAD

using Microsoft.AspNetCore.Authorization;
=======
>>>>>>> dev
using PaperlessREST.Entities;

namespace PaperlessREST.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class CorrespondentsApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="createCorrespondentRequest"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/correspondents")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreateCorrespondent")]
        [SwaggerResponse(statusCode: 200, type: typeof(CreateCorrespondentRequest), description: "Success")]
        public virtual IActionResult CreateCorrespondent([FromBody]CreateCorrespondentRequest createCorrespondentRequest)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(CreateCorrespondentRequest));
            string exampleJson = null;
            exampleJson = "{\r\n  \"owner\" : 6,\r\n  \"matching_algorithm\" : 0,\r\n  \"is_insensitive\" : true,\r\n  \"name\" : \"name\",\r\n  \"match\" : \"match\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<CreateCorrespondentRequest>(exampleJson)
            : default(CreateCorrespondentRequest);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <response code="204">Success</response>
        [HttpDelete]
        [Route("/api/correspondents/{id}")]
        [ValidateModelState]
        [SwaggerOperation("DeleteCorrespondent")]
        public virtual IActionResult DeleteCorrespondent([FromRoute (Name = "id")][Required]int id)
        {

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="page"></param>
        /// <param name="fullPerms"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/api/correspondents")]
        [ValidateModelState]
        [SwaggerOperation("GetCorrespondents")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetCorrespondents200Response), description: "Success")]
        public virtual IActionResult GetCorrespondents([FromQuery (Name = "page")]int? page, [FromQuery (Name = "full_perms")]bool? fullPerms)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(GetCorrespondents200Response));
            string exampleJson = null;
            exampleJson = "{\r\n  \"next\" : 6,\r\n  \"all\" : [ 5, 5 ],\r\n  \"previous\" : 1,\r\n  \"count\" : 0,\r\n  \"results\" : [ {\r\n    \"owner\" : 9,\r\n    \"matching_algorithm\" : 2,\r\n    \"document_count\" : 7,\r\n    \"is_insensitive\" : true,\r\n    \"permissions\" : {\r\n      \"view\" : {\r\n        \"groups\" : [ \"\", \"\" ],\r\n        \"users\" : [ \"\", \"\" ]\r\n      },\r\n      \"change\" : {\r\n        \"groups\" : [ \"\", \"\" ],\r\n        \"users\" : [ \"\", \"\" ]\r\n      }\r\n    },\r\n    \"name\" : \"name\",\r\n    \"match\" : \"match\",\r\n    \"id\" : 5,\r\n    \"last_correspondence\" : \"last_correspondence\",\r\n    \"slug\" : \"slug\"\r\n  }, {\r\n    \"owner\" : 9,\r\n    \"matching_algorithm\" : 2,\r\n    \"document_count\" : 7,\r\n    \"is_insensitive\" : true,\r\n    \"permissions\" : {\r\n      \"view\" : {\r\n        \"groups\" : [ \"\", \"\" ],\r\n        \"users\" : [ \"\", \"\" ]\r\n      },\r\n      \"change\" : {\r\n        \"groups\" : [ \"\", \"\" ],\r\n        \"users\" : [ \"\", \"\" ]\r\n      }\r\n    },\r\n    \"name\" : \"name\",\r\n    \"match\" : \"match\",\r\n    \"id\" : 5,\r\n    \"last_correspondence\" : \"last_correspondence\",\r\n    \"slug\" : \"slug\"\r\n  } ]\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<GetCorrespondents200Response>(exampleJson)
            : default(GetCorrespondents200Response);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="updateCorrespondentRequest"></param>
        /// <response code="200">Success</response>
        [HttpPut]
        [Route("/api/correspondents/{id}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("UpdateCorrespondent")]
        [SwaggerResponse(statusCode: 200, type: typeof(UpdateCorrespondent200Response), description: "Success")]
        public virtual IActionResult UpdateCorrespondent([FromRoute (Name = "id")][Required]int id, [FromBody]UpdateCorrespondentRequest updateCorrespondentRequest)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(UpdateCorrespondent200Response));
            string exampleJson = null;
            exampleJson = "{\r\n  \"owner\" : 5,\r\n  \"matching_algorithm\" : 6,\r\n  \"user_can_change\" : true,\r\n  \"document_count\" : 1,\r\n  \"is_insensitive\" : true,\r\n  \"name\" : \"name\",\r\n  \"match\" : \"match\",\r\n  \"id\" : 0,\r\n  \"last_correspondence\" : 5,\r\n  \"slug\" : \"slug\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<UpdateCorrespondent200Response>(exampleJson)
            : default(UpdateCorrespondent200Response);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
