version: '1.0'

services:
  paperlessrest:
    image: paperless-rest
    container_name: paperless-rest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 80:8080
    volumes:
      - ./src/PaperlessREST/:/app/src
      - /app/src/bin
      - /app/src/obj

  angular-app:
    image: paperless-ngx-ui
    ports:
      - 80:80
    volumes:
      - ./paperless-ngx-ui:/usr/share/nginx/html

  ngx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - /path/to/your/nginx/conf.d:/etc/nginx/conf.d
    
