version: '1.0'

services:
  paperless-rest:
    container_name: paperless-rest
    build:
      context: .
      args:
        - configuration=Debug
    ports:
      - 8080:8080
    volumes:
      - ./src:/src
      - /src/bin
      - /src/obj

  angular-app:
    image: nginx
    container_name: paperless-ui
    ports:
      - 80:80
    volumes:
      - ./src/paperless-ngx-ui/static:/usr/share/nginx/html/
      - ./src/config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - paperless-rest
  
  paperless-db:
    container_name: paperless-db
    image: postgres
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    ports:
      - 1433:5432  
    volumes:
      - db-data:/var/lib/postgressql/data

volumes:
  db-data: