version: '1.0'

services:
  paperless-rest:
    image: paperless-rest
    container_name: paperless-rest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8080:8080
    volumes:
      - ./src/PaperlessREST/:/app/src
      - /app/src/bin
      - /app/src/obj

  angular-app:
    image: nginx
    container_name: paperless-ui
    ports:
      - 80:80
    volumes:
      - ./src/paperless-ngx-ui/static:/usr/share/nginx/html/
      - ./src/config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - paperless-rest
  
  paperless-db:
    container_name: paperless-db
    image: postgres
    enviroment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWWORD: paperless
    ports:
      - 1433:1433
    volumes:
      - data:/var/lib/postgressql/data
    
  paperless-data:
    container_name: paperless-data
    volumes:
      - data