version: '1.0'

services:
  paperless-rest:
    image: paperless-rest
    container_name: paperless-rest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8080:8080
    volumes:
      - ./src/PaperlessREST/:/app/src
      - /app/src/bin
      - /app/src/obj

  angular-app:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src/paperless-ngx-ui/static:/usr/share/nginx/html/
      - ./src/config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - paperless-rest
